#3. 출력층 설계

In [1]:
import numpy as np
import seaborn as sns

- Label Encoding

In [2]:
from sklearn.preprocessing import LabelEncoder
items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','믹서']

# LabelEncoder 객체를 생성
encoder = LabelEncoder()
encoder.fit(items)                  # 학습, 훑어보는 일
labels = encoder.transform(items)   # 변환
labels

array([0, 1, 4, 5, 3, 2])

In [3]:
labels = encoder.fit_transform(items)   # 학습과 변환은 동시에 처리 가능
labels

array([0, 1, 4, 5, 3, 2])

In [4]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
le = LabelEncoder()
target = le.fit_transform(iris.species)     # iris['species']
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
le.inverse_transform([0,1,2])

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [13]:
iris['target'] = target     # iris DataFrame에 taget 열 추가
iris.tail()

sepal_length  sepal_width  petal_length  petal_width    species  target
145           6.7          3.0           5.2          2.3  virginica       2
146           6.3          2.5           5.0          1.9  virginica       2
147           6.5          3.0           5.2          2.0  virginica       2
148           6.2          3.4           5.4          2.3  virginica       2
149           5.9          3.0           5.1          1.8  virginica       2

In [14]:
iris.target.value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

- One-hot encoding

In [15]:
from sklearn.preprocessing import OneHotEncoder     # 사용하기가 조금 불편함
from tensorflow.keras.utils import to_categorical

In [16]:
# labels array([0, 1, 4, 5, 3, 2]) 값을 one-hot encoding한 결과
oh_labels = to_categorical(labels)
oh_labels

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)

In [17]:
Y_encoded = to_categorical(iris.target)
Y_encoded[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [20]:
from sklearn.datasets import load_iris
sk_iris = load_iris()
sk_iris.target                 # Scikit-learn의 iris 데이터는 레이블 인코딩 되어 있음

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

- softmax

In [21]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T

    x = x - np.max(x)           # overflow 방지용
    return np.exp(x) / np.sum(np.exp(x))

In [22]:
yhat = np.array([-1, 2.1, 3, 5])
softmax(yhat)

array([0.00207803, 0.04612802, 0.11345662, 0.83833733])

In [23]:
np.sum(softmax(yhat))

1.0

In [24]:
# 2차원인 경우
np.random.seed = 2022
yhat2 = np.random.normal(size=(3,4))
yhat2

array([[ 2.52533254,  2.16076309,  0.48856578, -2.45758897],
       [ 0.0777259 , -1.12917439, -1.37175456,  0.38273211],
       [ 1.0285843 ,  1.27011412,  0.20454371, -1.14790884]])

In [25]:
softmax(yhat2)

array([[0.5459113 , 0.379133  , 0.07121402, 0.00374168],
       [0.34596705, 0.10348672, 0.08119576, 0.46935047],
       [0.353946  , 0.45064243, 0.15526041, 0.04015116]])