#4. 신경망 평가

In [4]:
import numpy as np

In [1]:
from sklearn.datasets import load_digits
mnist = load_digits()
mnist.data.shape        # X(data)

(1797, 64)

In [2]:
mnist.target[:10]       # y(target)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Is it seven?

In [5]:
# 정답
target = np.array(mnist.target == 7, dtype=np.int32)
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32)

In [6]:
# 엉터리 예측값
prediction = np.zeros_like(target)
prediction[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

- 오차 행렬(Confusion matrix)

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    mnist.data, target, stratify=target, random_state=2022
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1347, 64), (450, 64), (1347,), (450,))

In [9]:
pred = np.zeros_like(y_test)
confusion_matrix(y_test, pred)

array([[405,   0],
       [ 45,   0]])

In [10]:
# 정확도
accuracy_score(y_test, pred)

0.9

In [11]:
from sklearn.metrics import precision_score, recall_score, f1_score